# Generated by Django 5.0.6 on 2024-08-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoBodega",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=255)),
                ("metros", models.IntegerField()),
                ("quimicos", models.BooleanField()),
                ("organicos", models.BooleanField()),
                ("hermetico", models.BooleanField()),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=45)),
                ("cuerpo", models.TextField()),
                ("imagen_url", models.CharField(max_length=255)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="noticias", to="main.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bodega",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=10)),
                (
                    "tipo_bodega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.tipobodega",
                    ),
                ),
            ],
        ),
    ]
